mp.setPlayerSprite(mp.playerSelector(mp.PlayerNumber.One), sprites.create(img`
    ..ddd...................................
    ..fffff.................................
    .fdddddfddd.............................
    .fdfffdfddddddd.........................
    .fdddddfdddddddddddd....................
    ..fdddfddddddddddddddddd................
    ..dfdfdddddddddddddddddddddd............
    ..dfdfddddddddddddddddddddddddddd.......
    ..dfdfddddddddddddddddddddddddddddddd...
    ..dfdfdddddddddddddddddddddddddddddddddd
    ..dfdfdddddddddddddddddddddddddddddddddd
    ..ddddddddddddddddddddddddddddddddddd...
    ..ddddddddddddddddddddddddddddddd.......
    ..dddddddddddddddddddddddddd............
    ..dddddddddddddddddddddd................
    ..dddddddddddddddddd....................
    ..ddddddddddddd.........................
    ..ddddddddd.............................
    ..ddddd.................................
    ..ddd...................................
    `, SpriteKind.Player))
mp.setPlayerState(mp.playerSelector(mp.PlayerNumber.One), MultiplayerState.score, 0)
info.setLife(3)
scene.setBackgroundImage(assets.image`baggrund2`)
scene.cameraFollowSprite(mp.getPlayerSprite(mp.playerSelector(mp.PlayerNumber.One)))
mp.moveWithButtons(mp.playerSelector(mp.PlayerNumber.One))
